### ISSUE TITLE
Does not work if JPEG images have been optimised using ImageOptim

### ISSUE THREAD

**Issue by raefa** [AppWerft/TiJSPDF#4]
It took me a while to figure this out! Image Optim (https://imageoptim.com/) must strip out the headers and jsPDF must rely on the headers to get the dimensions of the file. Should probably fail a little more gracefully than this:

```
[ERROR] [iphone, 8.4, 192.168.0.116] {
  "stack": "getJpegSize\naddImage\nsubmitForm",
  "column": 73,
  "line": 2163,
  "message": "getJpegSize could not find the size of the image"
}
```

**Comment by AppWerft** [comment]
Your suggestion?

**Comment by raefa** [comment]
Hmmm. Maybe we put a more descriptive error message in there. "getJpegSize could not find the size of the image. This may be because the headers of the JPEG have been removed or the image cannot be found."

**Comment by raefa** [comment]
I can't really think of anything better!

**Comment by AppWerft** [comment]
Thanks. I have changed the text
