### ISSUE TITLE
PDF with image added can't open in Adobe Acrobat - corrupted or damaged

### ISSUE THREAD

**Issue by raefa** [AppWerft/TiJSPDF#7]
On Android using Ti SDK 5.0.0.GA I am adding an image to a PDF. I am able to open the image using the Google PDF viewer but not Adobe Acrobat. I sent the message to my desktop and the same applies. I was able to view the image using "Preview" but not Adobe Acrobat. The error message says "The document cannot be opened because it is corrupted or damaged." If I remove the image from my PDF, the PDF will open in Acrobat. Odd right? 

@AppWerft I tried different types of images and started looking into the jsPDF library but pretty soon got lost. Sorry I can't be of assistance fixing this. Hopefully I am helping a little finding these things! :)

**Comment by AppWerft** [comment]
We have found the bug and will fix it. I think tomorrow we have a new version.

**Comment by raefa** [comment]
That last commit fixed it! :)
